source 'https://rubygems.org'

gem 'rake',         '~> 12.3'
gem 'hanami',       '~> 1.1'
gem 'hanami-model', '~> 1.1'

gem 'pg', '~> 0.21.0'

gem 'slim', '~> 3.0', '>= 3.0.9'

group :development do
  # Code reloading
  # See: http://hanamirb.org/guides/projects/code-reloading
  gem 'shotgun', '~> 0.9.2'
end

group :test, :development do
  gem 'dotenv', '~> 2.0'
end

group :test do
  gem 'rspec',    '~> 3.7'
  gem 'capybara', '~> 2.16', '>= 2.16.1'
end

group :production do
  # gem 'puma'
end
