version: '3.7'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_PATH: ${APP_PATH}
    command: yarn start
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - .:${APP_PATH}
    restart: unless-stopped
