version: "3.7"
services:
  web:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - type: tmpfs
        target: /app/tmp/pids
    command: rails s -b 0.0.0.0
    ports:
      - 9005:3000
    environment:
      RAILS_ENV: development
      # RAILS_MASTER_KEY:
