version: "3.7"
services:
  web:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - type: tmpfs
        target: /app/tmp/pids
    command: rails s -b 0.0.0.0
    ports:
      - 9005:3000
    restart: always
    environment:
      RAILS_ENV: development
      RAILS_MASTER_KEY: 7a0aa02b5314acd98ee1aa7a5113ddda

  cross:
    image: node:13.7.0-alpine3.10
    restart: always
    volumes:
      - ./cross-site:/app
    command: npx http-server -c-1 /app
    working_dir: /app
    ports:
      - 9006:8080
