version: "3.7"
services:
  web:
    build: .
    command: rails s
    volumes:
      - .:/usr/src/app
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - postgres
    ports:
      - 3000:3000

  postgres:
    image: postgres:latest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
