version: "3.7"
services:
  rails:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/usr/src/app
    ports:
      - 60100:3000
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - postgres
    environment:
      RAILS_MASTER_KEY: 9346703829d09fdc99738da279412ed2
  postgres:
    image: postgres:11.4-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always
volumes:
  pg-data:
