version: "3.7"
services:
  rails:
    build:
      context: rails
      dockerfile: ../cluster/development/rails.Dockerfile
    command: rails s -b 0.0.0.0
    tty: true
    stdin_open: true
    volumes:
      - ./rails:/usr/src/app
    ports:
      - 3000:3000
    environment:
      RAILS_MYSQL_DATABASE: dry_gems_development
      RAILS_MASTER_KEY: 3f4d2dbda7f3989dd78bfcbcdb1e2d85

    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        tag: rails

  kibana:
    image: kibana:7.2.0
    ports:
      - 5601:5601
    environment:
      elasticsearch.hosts: http://elasticsearch:9200
    depends_on:
      - fluentd

  fluentd:
    build:
      context: fluentd
      dockerfile: ../cluster/fluentd.Dockerfile
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./data/fluentd:/var/log/fluentd
    ports:
      - 24224:24224
      - 24224:24224/udp
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.2.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data

volumes:
  es-data:
