source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '5.1.4'
gem 'pg', '0.21'
gem 'puma', '3.12.4'
gem 'sass-rails', '5.0.7'
gem 'uglifier', '3.2'
gem 'turbolinks', '5.0.1'

gem 'slim', '3.0.9'
gem 'slim-rails', '3.1.3'

group :development, :test do
  gem 'byebug', '9.1',
    platforms: [:mri, :mingw, :x64_mingw]

  gem 'capybara', '2.16.1'
  gem 'selenium-webdriver', '3.8.0'

  gem 'rspec', '3.7'
  gem 'rspec-rails', '3.7.2'
  gem 'rails-controller-testing', '1.0.2'

  gem 'factory_bot', '4.8.2'
  gem 'factory_bot_rails', '4.8.2'

  gem 'database_cleaner', '1.6.2'
end

group :development do
  gem 'web-console', '3.5.1'
  gem 'listen', '3.1.5'
  gem 'spring', '2.0.2'
  gem 'spring-watcher-listen', '2.0.1'
end

gem 'tzinfo-data', '1.2017.3',
  platforms: [:mingw, :mswin, :x64_mingw, :jruby]
