version: '3.7'
services:
  web:
    build: .
    command: sh -c "rm -rf tmp/pids && rails s -b 0.0.0.0"
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - db

  db:
    image: postgres:11.3-alpine
    volumes:
      - ./tmp/data/postgres:/var/lib/postgresql/data
    restart: always

  cypress:
    image: cypress/included:3.3.1
    entrypoint: cypress open --project /e2e
    environment:
      - DISPLAY=:0
    volumes:
      - ./e2e:/e2e
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: always
    depends_on:
      - web
