source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails'
gem 'pg'
gem 'puma'
gem 'sass-rails'
gem 'uglifier'
gem 'turbolinks'
gem 'rails-i18n'
gem 'i18n-tasks'

gem 'slim'
gem 'slim-rails'

gem 'faker'

group :development, :test do
  gem 'byebug',
    platforms: [:mri, :mingw, :x64_mingw]

  gem 'capybara'
  gem 'selenium-webdriver'

  gem 'rspec'
  gem 'rspec-rails'
  gem 'rails-controller-testing'

  gem 'factory_bot'
  gem 'factory_bot_rails'

  gem 'database_cleaner'
end

group :development do
  gem 'web-console'
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'
end

gem 'tzinfo-data',
  platforms: [:mingw, :mswin, :x64_mingw, :jruby]
