version: "3.7"
services:
  web:
    build:
      context: web
      dockerfile: ../cluster/development/web.Dockerfile
    command: yarn start
    tty: true
    stdin_open: true
    ports:
      - 60080:3000
    volumes:
      - ./web:/usr/src/app
    restart: always

  server:
    build:
      context: server
      dockerfile: ../cluster/development/server.Dockerfile
    command: yarn start
    tty: true
    stdin_open: true
    ports:
      - 60000:3000
    volumes:
      - ./server:/usr/src/app
    restart: always
    environment:
      PORT: 3000
